sudo: true

language: scala
jdk:
- oraclejdk8
scala: 
- 2.11.5

script:
  - sbt clean coverage compile test && sbt coverageReport && sbt coverageAggregate

after_success:
  - bash <(curl -s https://codecov.io/bash)

