sudo: true

language: scala
jdk:
- oraclejdk11
scala: 
- 2.13.3

# Workaround for https://github.com/travis-ci/travis-ci/issues/7703
before_script:
  - sudo chmod +x /usr/local/bin/sbt

script:
  - sbt clean coverage compile test && sbt coverageReport && sbt coverageAggregate

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/8cdcfcf154f562f5bfc8
    on_success: change
    on_failure: always
    on_start: never
